#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          rightWheel,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftWheel,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void turnLeft(int power, int duration) {
	motor[leftWheel] = power;
	motor[rightWheel] = -power;
	wait1Msec(duration);
	motor[leftWheel] = 0;
	motor [rightWheel] = 0;
}

void turnRight(int power, int duration) {
	motor[leftWheel] = -power;
	motor[rightWheel] = power;
	wait1Msec(duration);
	motor[leftWheel] = 0;
	motor [rightWheel] = 0;
}

void goStraight(int power, int duration) {
	motor[leftWheel] = power;
	motor[rightWheel] = power;
	wait1Msec(duration);
	motor[leftWheel] = 0;
	motor [rightWheel] = 0;
}

task main()
{

}
